// @generated by scripts/build-client.js - DO NOT EDIT DIRECTLY.
// Edit modular source files in src/client/ instead.

window.__ModuleLoader__.load({
  id: "dsh-clinepass",
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    let React = require('react')

// --- src/client/constants.js ---
const NS = 'dsh-clinebot'
const PACKAGE_NAME = 'dsh-clinepass'
const ROUTE_PREFIX = '/dsh-clinebot'
const SNAPSHOT_LOADING = { status: 'loading', view: null }

// --- src/client/locales.js ---
const en = {
      title: 'ClineBot',
      subtitle: 'ClinePass models, keys, and usage.',
      'settings.loading': 'Loading ClineBot settings…',
      'settings.retry': 'Retry',
      'settings.unavailable': 'Settings mirror is unavailable on this host. Values can still be saved through the plugin API when the host settings service is writable.',
      'settings.mirror_loading': 'Settings mirror is still loading. The page is using the plugin status API.',
      'models.saved': 'Model settings saved.',
      'models.route_reasoning': 'Route default effort',
      'models.inherit': 'Inherit / unset',
      'models.provider_default': 'Provider default (send no effort)',
      'models.channel_unlisted': 'On the API, missing from the catalog',
      'models.unlisted_note': 'The subscription API returned this id, and the maintained catalog does not have it yet. Context, image, and reasoning stay unknown until they are added.',
      'models.opt_inherit': 'Inherit',
      'models.opt_text': 'Text only',
      'models.opt_image': 'Text and image',
      'models.opt_off': 'No reasoning control',
      'models.opt_vendor': 'Send catalog efforts',
      'models.enable_all': 'Register all',
      'models.unknown': 'unknown',
      'models.output_cap': 'Output cap',
      'models.request_budget': 'Request budget',
      'models.image_on': 'Image',
      'models.image_off': 'Text',
      'models.reasoning_off': 'Reasoning controls off',
      'models.edit': 'Edit',
      'models.close': 'Close',
      'models.count_hint': 'Token counts accept 1048576, 128k, or 1M. k is one thousand and M is one million.',
      'models.bad_number': 'Enter a token count such as 1048576, 128k, or 1M.',
      'models.context_ph': 'Context override (tokens)',
      'models.cap_ph': 'Output cap override',
      'models.budget_ph': 'Request budget override',
      'models.save': 'Save override',
      'models.restore': 'Restore inherited',
      'header.title': 'ClineBot (ClinePass) Provider',
      'header.sub': 'Models, credentials, and usage for this ClinePass subscription.',
      'badge.online': 'Host online ({latency} ms)',
      'badge.offline': 'Host unreachable',
      'badge.key_ok': 'Key ✓ ({source})',
      'badge.key_missing': 'Key missing',
      'badge.registered': 'DSH Registered ({count} models)',
      'badge.not_registered': 'Not registered',
      'key.title': 'Authorization & API key',
      'key.address': 'API address',
      'key.secret': 'API key',
      'key.get_key_label': 'Console',
      'key.desc': 'The key is stored by DSH credentials, not in the plugin settings. A name already set in the shell that launched dsh cannot be overwritten here.',
      'key.local_base': 'API address is a local mock ({url}). Quota and chat will not reach api.cline.bot until you save the official address.',
      'key.save_base': 'Save',
      'key.placeholder_has': '••••••••••••••••••••••••',
      'key.placeholder_empty': 'Paste ClinePass key (cline_...)',
      'key.show': 'Show',
      'key.hide': 'Hide',
      'key.save': 'Save Key',
      'key.saving': 'Saving…',
      'key.login_fast': 'Browser login',
      'key.login_waiting': 'Waiting for authorization in browser…',
      'key.env_label': 'Environment',
      'key.get_key': 'Get key in app.cline.bot console ↗',
      'key.saved_msg': 'Key saved to DSH Credentials. Validation: {status}',
      'key.saved_unverified': 'Key saved to the credential store. The connectivity check failed: {error}',
      'key.empty_err': 'Please enter an API key before saving',
      'accounts.title': 'Accounts',
      'accounts.col_name': 'Account',
      'accounts.col_ref': 'Credential',
      'accounts.col_status': 'Status',
      'accounts.col_action': 'Action',
      'accounts.configured': 'Configured ({source})',
      'accounts.missing': 'Missing key',
      'accounts.desc': 'The active account name is written to the ClineBot provider credential. Ordinary DSH turns then use that credential. This card does not count those turns.',
      'accounts.active_badge': 'Active',
      'accounts.pinned_badge': 'Pinned',
      'accounts.pin_btn': 'Pin Active',
      'accounts.add_btn': '+ Add Account',
      'accounts.label_placeholder': 'Account Label (e.g. Work)',
      'accounts.env_placeholder': 'CLINEBOT_API_KEY_2',
      'quota.title': 'ClinePass usage limits',
      'quota.desc': 'Official rolling window request limits from ClinePass',
      'quota.col_account': 'Account',
      'quota.col_plan': 'Plan',
      'quota.col_checked': 'Fetched',
      'quota.refresh': 'Refresh Quotas',
      'quota.checked_at': 'Fetched: {time}',
      'quota.refreshing': 'Refreshing…',
      'quota.refreshed_msg': 'Subscription quotas refreshed',
      'quota.col_limit': 'Limit',
      'quota.col_used': 'Used',
      'quota.col_meter': 'Meter',
      'quota.col_reset': 'Resets',
      'quota.window_5h': '5-hour',
      'quota.window_weekly': 'Weekly',
      'quota.window_monthly': 'Monthly',
      'quota.used': '{pct}% used',
      'quota.unknown': 'No usage figure returned',
      'quota.remaining': 'Remaining: {pct}%',
      'quota.reset_at': 'Reset: {time}',
      'models.title': 'Models ({enabled}/{total} enabled)',
      'models.desc': 'Checked models are registered. The output cap is not sent; the request budget is max_tokens.',
      'models.reasoning_tooltip': 'Supports thinking effort selection in composer model menu (Off / Low / Medium / High / Max)',
      'models.sync': 'Sync plan models',
      'models.syncing': 'Checking…',
      'models.synced_msg': 'Synchronized subscription models: {total} ({discovered} discovered from ClinePass)',
      'models.all': 'All',
      'models.vision': 'Vision',
      'models.coding': 'Coding',
      'models.recommended': 'Recommended',
      'models.th_active': 'On',
      'models.th_name': 'Model Name',
      'models.th_id': 'Model ID',
      'models.th_input': 'Input',
      'models.th_reasoning': 'Reasoning',
      'models.th_ctx': 'Context',
      'models.th_caps': 'Capabilities',
      'models.star': 'Star',
      'models.auto_new': 'New',
      'stats.title': 'This session',
      'stats.col_metric': 'Metric',
      'stats.col_value': 'Value',
      'stats.desc': 'Counts plugin smoke tests and /cline test only. Ordinary DSH turns are not included.',
      'stats.requests': 'Successful / Total Requests',
      'stats.tokens': 'Estimated Session Tokens',
      'stats.latency': 'Last Request Latency',
      'stats.last_req': 'Last Request Time',
      'diag.title': 'Diagnostics',
      'diag.col_latency': 'Latency',
      'diag.col_model': 'Model',
      'diag.col_reply': 'Reply',
      'diag.desc': 'Choose a model, test the configured API address, or sync the current models into DSH again.',
      'diag.model': 'Test model',
      'diag.smoke_btn': 'Smoke test',
      'diag.smoke_testing': 'Testing…',
      'diag.smoke_ok': 'Smoke test passed! Latency: {latency} ms',
      'diag.resync_btn': 'Sync again',
      'diag.resyncing': 'Syncing…',
      'diag.resynced_msg': 'Provider re-synced to DSH Models ({count} models)',
      'diag.unregister_btn': 'Unregister',
      'diag.unregistering': 'Removing…',
      'diag.unregistered_msg': 'Provider removed from DSH Models',
      'update.available': 'Update available: v{latestVersion} (current: v{currentVersion})',
      'update.btn': 'Update Now',
      'update.updating': 'Updating…',
      'update.done': 'Successfully updated to v{version}! Please restart DSH.',
      'update.failed': 'Update failed: {error}',
      'update.checking': 'Checking for updates…',
      'update.up_to_date': 'Up to date',
    }

    const zh = {
      title: 'ClineBot',
      subtitle: 'ClinePass 的模型、密钥和用量。',
      'settings.loading': '正在加载 ClineBot 设置…',
      'settings.retry': '重试',
      'settings.unavailable': '当前宿主没有可用的设置镜像。宿主设置服务可写时，仍可通过插件接口保存。',
      'settings.mirror_loading': '设置镜像仍在加载，页面先使用插件状态接口。',
      'models.saved': '模型设置已保存。',
      'models.route_reasoning': '路线默认思考档',
      'models.inherit': '继承 / 未设置',
      'models.provider_default': '提供方默认（不发送档位）',
      'models.channel_unlisted': '实际接口存在但维护目录缺失',
      'models.unlisted_note': '订阅接口已经返回这个 ID，维护目录里还没有。上下文、图像和思考档先保持未知，确认后再写入目录。',
      'models.opt_inherit': '继承目录',
      'models.opt_text': '仅文本',
      'models.opt_image': '文本和图像',
      'models.opt_off': '不发送思考档',
      'models.opt_vendor': '发送目录中的档位',
      'models.enable_all': '全部注册',
      'models.unknown': '未知',
      'models.output_cap': '最大输出',
      'models.request_budget': '请求预算',
      'models.image_on': '图像',
      'models.image_off': '文本',
      'models.reasoning_off': '不提供思考档',
      'models.edit': '编辑',
      'models.close': '收起',
      'models.count_hint': '可填 1048576、128k 或 1M。k 是千，M 是百万。',
      'models.bad_number': '请填写 token 数，例如 1048576、128k 或 1M。',
      'models.context_ph': '上下文覆盖（token）',
      'models.cap_ph': '最大输出覆盖',
      'models.budget_ph': '请求预算覆盖',
      'models.save': '保存覆盖',
      'models.restore': '恢复继承',
      'header.title': 'ClineBot (ClinePass) 模型服务商',
      'header.sub': '这个 ClinePass 订阅下的模型、密钥和用量。',
      'badge.online': '服务在线 ({latency} ms)',
      'badge.offline': '主机无法连接',
      'badge.key_ok': '密钥正常 ({source})',
      'badge.key_missing': '未配置密钥',
      'badge.registered': '已接入 DSH ({count} 个模型)',
      'badge.not_registered': '未接入 DSH',
      'key.title': '授权与 API 密钥',
      'key.address': 'API 地址',
      'key.secret': 'API 密钥',
      'key.get_key_label': '控制台',
      'key.desc': '密钥交给 DSH 凭据库保存，不写进插件配置。如果启动 dsh 的终端里已经有同名环境变量，这里的保存会被拒绝。',
      'key.local_base': '当前 API 地址是本地模拟服务（{url}）。在改回 https://api.cline.bot/api/v1 之前，刷新配额和对话都不会到达 ClinePass。',
      'key.save_base': '保存',
      'key.placeholder_has': '••••••••••••••••••••••••',
      'key.placeholder_empty': '粘贴 ClinePass 密钥 (cline_...)',
      'key.show': '显示',
      'key.hide': '隐藏',
      'key.save': '保存密钥',
      'key.saving': '正在保存…',
      'key.login_fast': '浏览器登录',
      'key.login_waiting': '等待在浏览器中完成授权…',
      'key.env_label': '环境变量',
      'key.get_key': '前往 app.cline.bot 控制台获取密钥 ↗',
      'key.saved_msg': '密钥已成功保存至 DSH 凭据服务。验证状态：{status}',
      'key.saved_unverified': '密钥已写入凭据库。连通性检查没有通过：{error}',
      'key.empty_err': '保存前请输入 API 密钥',
      'accounts.title': '账号',
      'accounts.col_name': '账号',
      'accounts.col_ref': '凭据',
      'accounts.col_status': '状态',
      'accounts.col_action': '操作',
      'accounts.configured': '已配置（{source}）',
      'accounts.missing': '未配置密钥',
      'accounts.desc': '活动账号的凭据名用于之后的对话。这里不统计那些对话。',
      'accounts.active_badge': '当前活动',
      'accounts.pinned_badge': '固定使用',
      'accounts.pin_btn': '设为活动',
      'accounts.add_btn': '+ 添加账号',
      'accounts.label_placeholder': '账号标签（例如：工作账号）',
      'accounts.env_placeholder': 'CLINEBOT_API_KEY_2',
      'quota.title': 'ClinePass 用量限额',
      'quota.desc': '来自 ClinePass 官方的实时滚动窗口用量限额',
      'quota.col_account': '账号',
      'quota.col_plan': '套餐',
      'quota.col_checked': '上次获取',
      'quota.refresh': '刷新配额',
      'quota.checked_at': '上次获取：{time}',
      'quota.refreshing': '正在刷新…',
      'quota.refreshed_msg': '订阅用量配额已刷新',
      'quota.col_limit': '限额',
      'quota.col_used': '已用',
      'quota.col_meter': '进度',
      'quota.col_reset': '重置',
      'quota.window_5h': '5 小时',
      'quota.window_weekly': '每周',
      'quota.window_monthly': '每月',
      'quota.used': '已使用 {pct}%',
      'quota.unknown': '没有返回用量',
      'quota.remaining': '剩余可用：{pct}%',
      'quota.reset_at': '重置时间：{time}',
      'models.title': '模型（已启用 {enabled}/{total}）',
      'models.desc': '勾选后注册到 DSH。最大输出不写入请求，请求预算才会作为 max_tokens。',
      'models.reasoning_tooltip': '支持在对话框上方模型菜单中选择思考强度（Off / Low / Medium / High / Max）',
      'models.sync': '同步订阅模型',
      'models.syncing': '正在同步…',
      'models.synced_msg': '已成功同步订阅模型：共 {total} 个（发现 {discovered} 个新模型）',
      'models.all': '全部',
      'models.vision': '视觉',
      'models.coding': '编程',
      'models.recommended': '推荐',
      'models.th_active': '启用',
      'models.th_name': '模型名称',
      'models.th_id': '模型标识符 (ID)',
      'models.th_input': '输入',
      'models.th_reasoning': '思考',
      'models.th_ctx': '上下文',
      'models.th_caps': '特性能力',
      'models.star': '推荐',
      'models.auto_new': '新上线',
      'stats.title': '本次会话',
      'stats.col_metric': '项目',
      'stats.col_value': '数值',
      'stats.desc': '只统计插件冒烟测试和 /cline test。普通 DSH 对话不计入。',
      'stats.requests': '成功 / 总请求次数',
      'stats.tokens': '会话累计 Token 估算',
      'stats.latency': '最近一次请求延迟',
      'stats.last_req': '最近请求时间',
      'diag.title': '诊断',
      'diag.col_latency': '延迟',
      'diag.col_model': '模型',
      'diag.col_reply': '回复',
      'diag.desc': '选择一个模型来测试当前 API 地址，或把模型重新同步到 DSH。',
      'diag.model': '测试模型',
      'diag.smoke_btn': '冒烟测试',
      'diag.smoke_testing': '正在测试…',
      'diag.smoke_ok': '冒烟测试通过！网络延迟：{latency} ms',
      'diag.resync_btn': '重新同步',
      'diag.resyncing': '正在同步…',
      'diag.resynced_msg': '模型服务已重新同步到 DSH ({count} 个模型)',
      'diag.unregister_btn': '注销',
      'diag.unregistering': '正在注销…',
      'diag.unregistered_msg': '已从 DSH 模型注册表中移除',
      'update.available': '发现新版本 v{latestVersion}（当前版本 v{currentVersion}）',
      'update.btn': '立即更新',
      'update.updating': '正在更新…',
      'update.done': '更新成功至 v{version}！请重启 DSH 服务生效。',
      'update.failed': '更新失败：{error}',
      'update.checking': '正在检查更新…',
      'update.up_to_date': '已是最新版本',
    }

    function makeT(dict, fallback) {
      return function t(key, vars) {
        let val = (dict && dict[key]) || (fallback && fallback[key]) || key
        if (vars && typeof val === 'string') {
          for (const k of Object.keys(vars)) {
            val = val.replace(new RegExp('\\{' + k + '\\}', 'g'), String(vars[k]))
          }
        }
        return val
      }
    }

// --- src/client/chevron.js ---
function FallbackChevron() {
  return React.createElement(
    'svg',
    { width: 14, height: 14, viewBox: '0 0 14 14', fill: 'none', 'aria-hidden': true },
    React.createElement('path', {
      d: 'M3.5 5.25L7 8.75L10.5 5.25',
      stroke: 'currentColor',
      strokeWidth: 1.5,
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    })
  )
}
let ChevronIcon = null
try {
  const primitives = require('@deepseek-ai/dsh-client-ui-primitives')
  ChevronIcon = primitives && (primitives.IconChevronDownOutline14 || primitives.IconChevronDownOutline)
} catch (_) {
  ChevronIcon = null
}
const Chevron = ChevronIcon || FallbackChevron

// --- src/client/styles.js ---
function ensureCss() {
      if (typeof document === 'undefined') return
      if (document.getElementById('dsh-clinebot-full-css')) return
      const style = document.createElement('style')
      style.id = 'dsh-clinebot-full-css'
      style.dataset.dshPlugin = NS
      style.textContent = `
.cb-page{display:flex;flex-direction:column;gap:16px;padding:0 0 24px;max-width:none;min-width:0}
.cb-status{display:flex;flex-wrap:wrap;gap:8px}
.cb-chevron{display:inline-flex;align-items:center;justify-content:center;transition:transform .16s ease;color:var(--dsw-alias-label-tertiary)}
.cb-chevron-open{transform:rotate(180deg)}
.cb-header{display:flex;flex-direction:column;gap:8px;padding-bottom:16px;border-bottom:1px solid var(--dsw-alias-border-l2)}
.cb-page-title{font-size:22px;font-weight:700;color:var(--dsw-alias-label-primary);display:flex;flex-wrap:wrap;align-items:center;gap:10px}
.cb-page-sub{font-size:14px;color:var(--dsw-alias-label-secondary);line-height:1.5}

.cb-section-card{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:12px;padding:16px;display:flex;flex-direction:column;gap:12px;min-width:0}
.cb-section-card .cb-field{margin:0}
.cb-section-title{font-size:16px;font-weight:600;color:var(--dsw-alias-label-primary);display:flex;align-items:center;justify-content:space-between}
.cb-section-title-stack{flex-direction:column;align-items:flex-start;gap:10px}
.cb-section-desc{font-size:13px;color:var(--dsw-alias-label-secondary);margin-top:-6px;line-height:1.4}

.cb-row{display:flex;flex-wrap:wrap;gap:10px;align-items:center}
.cb-field{display:flex;flex-direction:column;gap:6px;margin:12px 0}
.cb-field-label{font-size:12px;color:var(--dsw-alias-label-secondary)}
.cb-grid-2{display:grid;grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));gap:14px}

.cb-badge{font-size:12px;padding:3px 10px;border-radius:999px;border:1px solid var(--dsw-alias-border-l2);display:inline-flex;align-items:center;gap:5px;font-weight:500}
.cb-badge-ok{border-color:var(--dsw-alias-state-success-primary);color:var(--dsw-alias-state-success-primary);background:color-mix(in srgb, var(--dsw-alias-state-success-primary) 8%, transparent)}
.cb-badge-warn{border-color:var(--dsw-alias-state-warning-primary);color:var(--dsw-alias-state-warning-primary);background:color-mix(in srgb, var(--dsw-alias-state-warning-primary) 8%, transparent)}
.cb-badge-bad{border-color:var(--dsw-alias-state-error-primary);color:var(--dsw-alias-state-error-primary);background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 8%, transparent)}

.cb-input{height:36px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);border-radius:8px;padding:0 12px;font-size:13px;width:100%;box-sizing:border-box}
.cb-input:focus{outline:none;border-color:var(--dsw-alias-state-brand-primary)}
.cb-input-group{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
.cb-input-group .cb-input{flex:1 1 160px;width:auto;min-width:0}

.cb-btn{appearance:none;font:inherit;cursor:pointer;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:7px 12px;font-size:13px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font-weight:500;display:inline-flex;align-items:center;justify-content:center;gap:6px;white-space:nowrap;flex:0 0 auto;transition:all .15s ease}
.cb-btn:hover:not(:disabled){background:var(--dsw-alias-bg-layer-4, var(--dsw-alias-bg-layer-2));border-color:var(--dsw-alias-label-dimmed, var(--dsw-alias-border-l2))}
.cb-btn-active{border-color:var(--dsw-alias-state-brand-primary);color:var(--dsw-alias-state-brand-primary);background:color-mix(in srgb, var(--dsw-alias-state-brand-primary) 8%, transparent)}
.cb-btn-primary{background:var(--dsw-alias-label-primary);color:var(--dsw-alias-bg-layer-3);border-color:transparent}
.cb-btn-primary:hover:not(:disabled){background:var(--dsw-alias-label-primary) !important;color:var(--dsw-alias-bg-layer-3) !important;opacity:0.88;visibility:visible !important}
.cb-btn-danger{color:var(--dsw-alias-state-error-primary);border-color:color-mix(in srgb, var(--dsw-alias-state-error-primary) 30%, transparent)}
.cb-btn-danger:hover:not(:disabled){background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 12%, transparent) !important;border-color:color-mix(in srgb, var(--dsw-alias-state-error-primary) 50%, transparent)}
.cb-btn-disabled{opacity:0.5;cursor:not-allowed}

.cb-bar-container{display:flex;flex-direction:column;gap:6px;padding:12px 14px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-2)}
.cb-bar-head{display:flex;justify-content:space-between;font-size:13px;font-weight:500;color:var(--dsw-alias-label-primary)}
.cb-bar-track{width:100%;height:10px;border-radius:999px;background:var(--dsw-alias-bg-layer-1);overflow:hidden;border:1px solid var(--dsw-alias-border-l2)}
.cb-bar-fill{height:100%;border-radius:999px;transition:width .3s;min-width:0}
.cb-bar-fill-ok{background:var(--dsw-alias-state-success-primary)}
.cb-bar-fill-warn{background:var(--dsw-alias-state-warning-primary)}
.cb-bar-fill-bad{background:var(--dsw-alias-state-error-primary)}
.cb-quota-meta{margin-top:0}
.cb-quota-meta th{width:88px;white-space:nowrap}
.cb-quota-meta td{white-space:normal;overflow-wrap:anywhere}
.cb-quota{margin-top:4px}
.cb-quota th,.cb-quota td{white-space:nowrap}
.cb-quota th:nth-child(2),.cb-quota td:nth-child(2){text-align:right;width:76px}
.cb-quota td:nth-child(3){width:42%}
.cb-quota-pct{font-variant-numeric:tabular-nums;font-size:18px;font-weight:700}
.cb-quota-pct-ok{color:var(--dsw-alias-state-success-primary)}
.cb-quota-pct-warn{color:var(--dsw-alias-state-warning-primary)}
.cb-quota-pct-bad{color:var(--dsw-alias-state-error-primary)}
.cb-quota-reset{font-variant-numeric:tabular-nums;color:var(--dsw-alias-label-secondary)}
.cb-bar-meta{display:flex;justify-content:space-between;font-size:12px;color:var(--dsw-alias-label-secondary)}

.cb-num{font-variant-numeric:tabular-nums;text-align:right;white-space:nowrap}
.cb-model{display:grid;grid-template-columns:22px minmax(0,1fr);gap:8px 10px;align-items:start;padding:12px 0;border-bottom:1px solid var(--dsw-alias-border-l2)}
.cb-model-head{display:flex;align-items:center;justify-content:space-between;gap:8px}
.cb-model-id{display:block;margin-top:2px;font-family:ui-monospace,monospace;font-size:12px;color:var(--dsw-alias-label-secondary);word-break:break-all}
.cb-metrics{display:flex;flex-wrap:wrap;gap:8px 16px;margin-top:8px}
.cb-metric{display:flex;flex-direction:column;gap:2px;min-width:64px}
.cb-metric b{font-size:13px;font-weight:650;font-variant-numeric:tabular-nums;color:var(--dsw-alias-label-primary)}
.cb-metric span{font-size:11px;color:var(--dsw-alias-label-secondary)}
.cb-table th,.cb-table td{white-space:nowrap}
.cb-editor{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;padding:4px 0 8px}
.cb-editor .cb-field{margin:0}
.cb-editor-note{grid-column:1/-1}
.cb-editor-actions{grid-column:1/-1;display:flex;gap:8px;flex-wrap:wrap}
.cb-editor .cb-alert-ok,.cb-editor .cb-alert-bad{grid-column:1/-1;margin:0}
.cb-facts th{width:140px}
.cb-facts a{color:var(--dsw-alias-state-brand-primary)}
.cb-table{width:100%;border-collapse:collapse;margin-top:8px}
.cb-table th{text-align:left;font-size:12px;color:var(--dsw-alias-label-secondary);padding:8px 10px;border-bottom:1px solid var(--dsw-alias-border-l2);font-weight:600}
.cb-table td{padding:10px;border-bottom:1px solid var(--dsw-alias-border-l2);font-size:13px;color:var(--dsw-alias-label-primary)}
.cb-table tr:hover{background:var(--dsw-alias-bg-layer-2)}

.cb-alert-ok{padding:10px 14px;border-radius:8px;background:color-mix(in srgb, var(--dsw-alias-state-success-primary) 10%, transparent);color:var(--dsw-alias-state-success-primary);font-size:13px}
.cb-alert-bad{padding:10px 14px;border-radius:8px;background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 10%, transparent);color:var(--dsw-alias-state-error-primary);font-size:13px}
.cb-alert-err{padding:10px 14px;border-radius:8px;background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 10%, transparent);color:var(--dsw-alias-state-error-primary);font-size:13px}
.cb-banner-warning{padding:12px 16px;border-radius:8px;background:color-mix(in srgb, var(--dsw-alias-state-warning-primary) 12%, transparent);border:1px solid var(--dsw-alias-state-warning-primary);color:var(--dsw-alias-state-warning-primary);font-size:13px;display:flex;align-items:center;gap:10px;font-weight:500}
.cb-banner-exhausted{padding:12px 16px;border-radius:8px;background:color-mix(in srgb, var(--dsw-alias-state-error-primary) 12%, transparent);border:1px solid var(--dsw-alias-state-error-primary);color:var(--dsw-alias-state-error-primary);font-size:13px;display:flex;align-items:center;gap:10px;font-weight:600}
.cb-stat-box{padding:12px 14px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-2);display:flex;flex-direction:column;gap:4px}
.cb-stat-val{font-size:18px;font-weight:700;color:var(--dsw-alias-label-primary)}
.cb-stat-lbl{font-size:12px;color:var(--dsw-alias-label-secondary)}
.cb-preview{padding:12px;border-radius:8px;background:var(--dsw-alias-bg-layer-2);font-family:monospace;font-size:12px;white-space:pre-wrap;word-break:break-all;border:1px solid var(--dsw-alias-border-l2)}
`
      document.head.appendChild(style)
    }

// --- src/client/error-boundary.js ---
function createErrorBoundary() {
  try {
    if (!React || typeof React.Component !== 'function') {
      return function NoopBoundary(props) { return props?.children || null }
    }
    return class ClientErrorBoundary extends React.Component {
      constructor(props) {
        super(props)
        this.state = { hasError: false, error: null }
      }
      static getDerivedStateFromError(error) {
        return { hasError: true, error }
      }
      componentDidCatch(error, info) {
        console.warn('[dsh-clinebot] Client render error caught by boundary:', error, info)
      }
      render() {
        if (this.state.hasError) {
          return React.createElement(
            'div',
            { className: 'cb-alert-err' },
            React.createElement('strong', null, '⚠️ ClineBot UI Error: '),
            String(this.state.error?.message || this.state.error || 'Unknown rendering error'),
            React.createElement(
              'button',
              {
                type: 'button',
                className: 'cb-btn',
                style: { marginLeft: '12px', padding: '2px 8px', fontSize: '11px' },
                onClick: () => this.setState({ hasError: false, error: null }),
              },
              'Retry'
            )
          )
        }
        return this.props.children
      }
    }
  } catch (e) {
    return function FallbackBoundary(props) { return props?.children || null }
  }
}
const ErrorBoundary = createErrorBoundary()

// --- src/client/progress-bar.js ---
function formatResetTime(isoString) {
  if (!isoString) return ''
  try {
    const d = new Date(isoString)
    if (Number.isNaN(d.getTime())) return ''
    return d.toLocaleString(undefined, {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false,
    })
  } catch {
    return ''
  }
}

function ProgressBar({ label, known = true, percentUsed, resetsAt, t }) {
  const pct = known ? Math.max(0, Math.min(100, Math.round(Number(percentUsed)))) : null
  const tone = pct == null ? '' : pct >= 95 ? 'bad' : pct >= 80 ? 'warn' : 'ok'
  const resetLabel = formatResetTime(resetsAt)
  return React.createElement(
    'tr',
    null,
    React.createElement('th', { scope: 'row' }, label),
    React.createElement(
      'td',
      { className: pct == null ? 'cb-quota-pct' : `cb-quota-pct cb-quota-pct-${tone}` },
      pct == null ? t('quota.unknown') : `${pct}%`,
    ),
    React.createElement(
      'td',
      null,
      React.createElement(
        'div',
        { className: 'cb-bar-track', role: 'meter', 'aria-valuemin': 0, 'aria-valuemax': 100, 'aria-valuenow': pct == null ? undefined : pct, 'aria-label': label },
        React.createElement('div', {
          className: pct == null ? 'cb-bar-fill' : `cb-bar-fill cb-bar-fill-${tone}`,
          style: { width: pct == null ? '0%' : `${pct}%`, minWidth: pct > 0 ? '6px' : 0 },
        }),
      ),
    ),
    React.createElement('td', { className: 'cb-quota-reset' }, resetLabel || '—'),
  )
}

// --- src/client/components/update-banner.js ---
function UpdateBanner({ updateState, handleTriggerUpdate, t }) {
  return React.createElement(
    React.Fragment,
    null,
    React.createElement(
      'div',
      {
        className: 'cb-row',
        style: {
          padding: '10px 14px',
          borderRadius: '8px',
          border: '1px solid var(--dsw-alias-border-l2)',
          background: 'var(--dsw-alias-bg-layer-2)',
          justifyContent: 'space-between',
        }
      },
      React.createElement(
        'div',
        { style: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px' } },
        updateState.currentVersion
          ? React.createElement('span', { style: { color: 'var(--dsw-alias-label-secondary)', fontWeight: 500 } },
              `v${updateState.currentVersion}`
            )
          : null,
        updateState.checking
          ? React.createElement('span', { style: { color: 'var(--dsw-alias-label-tertiary)', fontSize: '12px' } },
              t('update.checking')
            )
          : updateState.updateAvailable
            ? React.createElement('span', { className: 'cb-badge cb-badge-warn' },
                t('update.available', { latestVersion: updateState.latestVersion, currentVersion: updateState.currentVersion })
              )
            : React.createElement('span', { className: 'cb-badge cb-badge-ok' },
                '✓ ' + t('update.up_to_date')
              )
      ),
      updateState.updateAvailable
        ? React.createElement(
            'button',
            {
              type: 'button',
              className: 'cb-btn cb-btn-primary',
              disabled: updateState.updating,
              onClick: handleTriggerUpdate,
              style: { padding: '5px 12px', fontSize: '12px' }
            },
            updateState.updating ? t('update.updating') : t('update.btn')
          )
        : null
    ),
    updateState.notice ? React.createElement('div', { className: 'cb-alert-ok' }, '✓ ' + updateState.notice) : null,
    updateState.error ? React.createElement('div', { className: 'cb-alert-err' }, updateState.error) : null
  )
}

// --- src/client/components/key-section.js ---
function KeySection({ keyPresent, apiKeyInput, setApiKeyInput, showKey, setShowKey, busy, draft, baseUrlInput, setBaseUrlInput, handleSaveKey, handleSaveBaseUrl, handleFastLogin, t }) {
  const base = String(draft?.baseUrl || '')
  const localApi = /^https?:\/\/(127\.0\.0\.1|localhost|\[::1\])(?::|\/|$)/i.test(base)
  return React.createElement(
    'div',
    { className: 'cb-section-card' },
    React.createElement('div', { className: 'cb-section-title' }, t('key.title')),
    React.createElement('div', { className: 'cb-section-desc' }, t('key.desc')),
    localApi ? React.createElement('div', { className: 'cb-banner-warning' }, t('key.local_base', { url: base })) : null,
    React.createElement(
      'label',
      { className: 'cb-field' },
      React.createElement('span', { className: 'cb-field-label' }, t('key.address')),
      React.createElement(
        'div',
        { className: 'cb-input-group' },
        React.createElement('input', {
          className: 'cb-input',
          value: baseUrlInput,
          onChange: (event) => setBaseUrlInput(event.target.value),
          spellCheck: false,
        }),
        React.createElement('button', {
          type: 'button',
          className: 'cb-btn',
          disabled: !!busy,
          onClick: handleSaveBaseUrl,
        }, busy === 'save-base' ? t('key.saving') : t('key.save_base')),
      ),
    ),
    React.createElement(
      'label',
      { className: 'cb-field' },
      React.createElement('span', { className: 'cb-field-label' }, t('key.secret')),
      React.createElement(
      'div',
      { className: 'cb-input-group' },
      React.createElement('input', {
        className: 'cb-input',
        type: showKey ? 'text' : 'password',
        placeholder: keyPresent ? t('key.placeholder_has') : t('key.placeholder_empty'),
        value: apiKeyInput,
        onChange: (e) => setApiKeyInput(e.target.value),
      }),
      React.createElement(
        'button',
        {
          type: 'button',
          className: 'cb-btn',
          onClick: () => setShowKey((v) => !v),
        },
        showKey ? t('key.hide') : t('key.show')
      ),
      React.createElement(
        'button',
        {
          type: 'button',
          className: 'cb-btn cb-btn-primary',
          disabled: !!busy || !String(apiKeyInput || '').trim(),
          onClick: handleSaveKey,
        },
        busy === 'save-key' ? t('key.saving') : t('key.save')
      ),
      React.createElement(
        'button',
        {
          type: 'button',
          className: 'cb-btn',
          disabled: !!busy,
          onClick: handleFastLogin,
        },
        busy === 'fast-login' ? '…' : t('key.login_fast')
      )
      ),
    ),
    React.createElement(
      'table',
      { className: 'cb-table cb-facts' },
      React.createElement('tbody', null,
        React.createElement('tr', null,
          React.createElement('th', { scope: 'row' }, t('key.env_label')),
          React.createElement('td', null, React.createElement('code', null, draft.apiKeyEnv || 'CLINEBOT_API_KEY')),
        ),
        React.createElement('tr', null,
          React.createElement('th', { scope: 'row' }, t('key.get_key_label')),
          React.createElement('td', null, React.createElement('a', {
            href: 'https://app.cline.bot',
            target: '_blank',
            rel: 'noreferrer',
          }, t('key.get_key'))),
        ),
      ),
    )
  )
}

// --- src/client/components/accounts-section.js ---
function AccountsSection({ status, busy, handlePinAccount, t }) {
  if (!status.accounts || !status.accounts.length) return null
  return React.createElement(
    'div',
    { className: 'cb-section-card' },
    React.createElement('div', { className: 'cb-section-title' }, t('accounts.title')),
    React.createElement('div', { className: 'cb-section-desc' }, t('accounts.desc')),
    React.createElement(
      'table',
      { className: 'cb-table' },
      React.createElement(
        'thead',
        null,
        React.createElement(
          'tr',
          null,
          React.createElement('th', null, t('accounts.col_name')),
          React.createElement('th', null, t('accounts.col_ref')),
          React.createElement('th', null, t('accounts.col_status')),
          React.createElement('th', null, t('accounts.col_action'))
        )
      ),
      React.createElement(
        'tbody',
        null,
        status.accounts.map((acc) => {
          const isActive = status.activeAccount === acc.apiKeyEnv || (!status.activeAccount && acc.id === 'default')
          return React.createElement(
            'tr',
            { key: acc.id },
            React.createElement('td', null, React.createElement('strong', null, acc.label)),
            React.createElement('td', null, React.createElement('code', null, acc.apiKeyEnv)),
            React.createElement(
              'td',
              null,
              acc.present
                ? React.createElement('span', { className: 'cb-badge cb-badge-ok' }, t('accounts.configured', { source: acc.source }))
                : React.createElement('span', { className: 'cb-badge cb-badge-warn' }, t('accounts.missing')),
              isActive
                ? React.createElement('span', { className: 'cb-badge cb-badge-ok', style: { marginLeft: '6px' } }, t('accounts.active_badge'))
                : null
            ),
            React.createElement(
              'td',
              { style: { textAlign: 'right' } },
              !isActive && acc.present
                ? React.createElement(
                    'button',
                    {
                      type: 'button',
                      className: 'cb-btn',
                      style: { padding: '4px 8px', fontSize: '11px' },
                      disabled: !!busy,
                      onClick: () => handlePinAccount(acc.apiKeyEnv),
                    },
                    t('accounts.pin_btn')
                  )
                : null
            )
          )
        })
      )
    )
  )
}

// --- src/client/components/quota-section.js ---
function QuotaSection({ keyPresent, status, usage, busy, handleRefreshQuota, t }) {
  const checkedAt = formatResetTime(usage?.checkedAt)
  return React.createElement(
    React.Fragment,
    null,
    status.quotaWarning
      ? React.createElement(
          'div',
          { className: status.quotaWarning.level === 'exhausted' ? 'cb-banner-exhausted' : 'cb-banner-warning' },
          React.createElement('span', { style: { fontSize: '16px' } }, status.quotaWarning.level === 'exhausted' ? '🚨' : '⚠️'),
          React.createElement(
            'div',
            { style: { flex: 1 } },
            React.createElement('div', null, status.quotaWarning.message),
            status.quotaWarning.resetsAt
              ? React.createElement(
                  'div',
                  { style: { fontSize: '11px', opacity: 0.9, marginTop: '2px' } },
                  t('quota.reset_at', { time: formatResetTime(status.quotaWarning.resetsAt) })
                )
              : null
          )
        )
      : null,
    keyPresent
      ? React.createElement(
          'div',
          { className: 'cb-section-card' },
          React.createElement(
            'div',
            { className: 'cb-section-title' },
            t('quota.title'),
            React.createElement(
              'button',
              {
                type: 'button',
                className: 'cb-btn',
                disabled: !!busy,
                onClick: handleRefreshQuota,
              },
              busy === 'refresh-quota' ? t('quota.refreshing') : t('quota.refresh')
            )
          ),
          React.createElement(
            'table',
            { className: 'cb-table cb-facts cb-quota-meta' },
            React.createElement('tbody', null,
              [
                [t('quota.col_account'), usage?.user?.email || '—'],
                [t('quota.col_plan'), usage?.plan || '—'],
                [t('quota.col_checked'), checkedAt || '—'],
              ].map(([label, value]) => React.createElement('tr', { key: label },
                React.createElement('th', { scope: 'row' }, label),
                React.createElement('td', null, value),
              )),
            ),
          ),
          React.createElement(
            'table',
            { className: 'cb-table cb-quota' },
            React.createElement(
              'thead',
              null,
              React.createElement(
                'tr',
                null,
                React.createElement('th', null, t('quota.col_limit')),
                React.createElement('th', null, t('quota.col_used')),
                React.createElement('th', null, t('quota.col_meter')),
                React.createElement('th', null, t('quota.col_reset')),
              ),
            ),
            React.createElement(
              'tbody',
              null,
            React.createElement(ProgressBar, {
              label: t('quota.window_5h'),
              known: typeof usage?.windows?.fiveHour?.percentUsed === 'number',
              percentUsed: usage?.windows?.fiveHour?.percentUsed,
              remainingPercent: usage?.windows?.fiveHour?.remainingPercent,
              resetsAt: usage?.windows?.fiveHour?.resetsAt,
              t,
            }),
            React.createElement(ProgressBar, {
              label: t('quota.window_weekly'),
              known: typeof usage?.windows?.weekly?.percentUsed === 'number',
              percentUsed: usage?.windows?.weekly?.percentUsed,
              remainingPercent: usage?.windows?.weekly?.remainingPercent,
              resetsAt: usage?.windows?.weekly?.resetsAt,
              t,
            }),
            React.createElement(ProgressBar, {
              label: t('quota.window_monthly'),
              known: typeof usage?.windows?.monthly?.percentUsed === 'number',
              percentUsed: usage?.windows?.monthly?.percentUsed,
              remainingPercent: usage?.windows?.monthly?.remainingPercent,
              resetsAt: usage?.windows?.monthly?.resetsAt,
              t,
            }),
            ),
          )
        )
      : null
  )
}

// --- src/client/token-count.js ---
function parseTokenCount(value) {
  const text = String(value || '').trim().replace(/,/g, '').replace(/\s+/g, '')
  if (!text) return { ok: true, value: 'inherit' }
  const match = text.match(/^(\d+(?:\.\d+)?)([kKmM])?$/)
  if (!match) return { ok: false, value: 'inherit' }
  const amount = Number(match[1])
  if (!Number.isFinite(amount) || amount <= 0) return { ok: false, value: 'inherit' }
  const suffix = (match[2] || '').toLowerCase()
  const scaled = suffix === 'k' ? amount * 1000 : suffix === 'm' ? amount * 1_000_000 : amount
  const rounded = Math.round(scaled)
  if (!Number.isInteger(rounded) || rounded <= 0) return { ok: false, value: 'inherit' }
  return { ok: true, value: rounded }
}

// --- src/client/components/models-section.js ---
function optionLabel(mode, t) {
  if (mode === 'inherit') return t('models.opt_inherit')
  if (mode === 'text') return t('models.opt_text')
  if (mode === 'text+image') return t('models.opt_image')
  if (mode === 'off') return t('models.opt_off')
  if (mode === 'vendor') return t('models.opt_vendor')
  return mode
}

function formatK(value) {
  const n = Number(value)
  if (!Number.isFinite(n) || n <= 0) return '—'
  if (n % 1024 === 0) return `${n / 1024}k`
  return `${Math.round(n / 1000)}k`
}

function reasoningLabel(model, t) {
  if (model.reasoningSource === 'user-off') return t('models.reasoning_off')
  const active = model.reasoningLevelIds || []
  if (active.length) return active.join(' / ')
  const available = model.catalogReasoningLevels || []
  if (available.length) return available.join(' / ')
  return '—'
}

function ModelsSection({
  modelsList,
  enabledSet,
  enabledCount,
  totalCount,
  keyPresent,
  busy,
  modelsFilter,
  providerReasoning,
  handleSyncPlanModels,
  handleSetModelsFilter,
  handleToggleModel,
  saveModelPatch,
  t,
}) {
  const [editing, setEditing] = React.useState('')
  const [form, setForm] = React.useState(null)
  const [notice, setNotice] = React.useState(null)

  function openEditor(model) {
    const override = model.override || {}
    setEditing(model.id)
    setForm({
      contextWindow: override.contextWindow === 'inherit' ? '' : String(override.contextWindow ?? ''),
      outputCapability: override.outputCapability === 'inherit' ? '' : String(override.outputCapability ?? ''),
      requestOutputBudget: override.requestOutputBudget === 'inherit' ? '' : String(override.requestOutputBudget ?? ''),
      inputMode: override.inputMode || 'inherit',
      reasoningMode: override.reasoningMode || 'inherit',
    })
  }

  async function saveEditor(model, restore) {
    const counts = restore ? null : {
      contextWindow: parseTokenCount(form.contextWindow),
      outputCapability: parseTokenCount(form.outputCapability),
      requestOutputBudget: parseTokenCount(form.requestOutputBudget),
    }
    if (counts && (!counts.contextWindow.ok || !counts.outputCapability.ok || !counts.requestOutputBudget.ok)) {
      setNotice({ id: model.id, ok: false, text: t('models.bad_number') })
      return
    }
    const result = await saveModelPatch({
      modelOverride: {
        id: model.id,
        contextWindow: restore ? 'inherit' : counts.contextWindow.value,
        outputCapability: restore ? 'inherit' : counts.outputCapability.value,
        requestOutputBudget: restore ? 'inherit' : counts.requestOutputBudget.value,
        inputMode: restore ? 'inherit' : form.inputMode,
        reasoningMode: restore ? 'inherit' : form.reasoningMode,
      },
    })
    if (result) setNotice({ id: model.id, ok: result.ok, text: result.message })
  }

  return React.createElement(
    'div',
    { className: 'cb-section-card' },
    React.createElement(
      'div',
      { className: 'cb-section-title cb-section-title-stack' },
      t('models.title', { enabled: enabledCount, total: totalCount }),
      React.createElement(
        'div',
        { className: 'cb-row' },
        [['all', 'models.all'], ['vision', 'models.vision'], ['coding', 'models.coding'], ['recommended', 'models.recommended']].map(([id, key]) => React.createElement(
          'button',
          {
            key: id,
            type: 'button',
            className: modelsFilter === id ? 'cb-btn cb-btn-active' : 'cb-btn',
            onClick: () => handleSetModelsFilter(id),
          },
          t(key),
        )),
        React.createElement('button', { type: 'button', className: 'cb-btn', disabled: !!busy, onClick: () => saveModelPatch({ selectionKind: 'all-except-disabled', disabledModels: [], explicitModels: [] }) }, t('models.enable_all')),
        React.createElement('button', { type: 'button', className: 'cb-btn', disabled: !!busy || !keyPresent, onClick: handleSyncPlanModels }, busy === 'sync-models' ? t('models.syncing') : t('models.sync')),
      )
    ),
    React.createElement('div', { className: 'cb-section-desc' }, t('models.desc')),
    React.createElement(
      'label',
      { className: 'cb-field' },
      React.createElement('span', { className: 'cb-field-label' }, t('models.route_reasoning')),
      React.createElement('select', {
        className: 'cb-input',
        value: providerReasoning || '',
        onChange: (event) => saveModelPatch({ providerReasoning: event.target.value }),
      }, ['', 'low', 'high', 'max'].map((level) => React.createElement('option', { key: level || 'inherit', value: level }, level || t('models.provider_default'))))
    ),
    React.createElement(
      'div',
      { className: 'cb-model-list' },
      modelsList.map((model) => React.createElement(
        'div',
        { key: model.id },
        React.createElement('div', { className: 'cb-model' },
          React.createElement('input', {
            type: 'checkbox',
            checked: enabledSet.has(model.id),
            onChange: () => handleToggleModel(model.id),
            'aria-label': model.name,
          }),
          React.createElement('div', { className: 'cb-model-main' },
            React.createElement('div', { className: 'cb-model-head' },
              React.createElement('strong', null, model.name),
              React.createElement('button', {
                type: 'button',
                className: 'cb-btn',
                onClick: () => (editing === model.id ? setEditing('') : openEditor(model)),
              }, editing === model.id ? t('models.close') : t('models.edit')),
            ),
            React.createElement('span', { className: 'cb-model-id' }, model.id),
            model.channelListed ? null : React.createElement('span', { className: 'cb-badge cb-badge-warn' }, t('models.channel_unlisted')),
            React.createElement('div', { className: 'cb-metrics' },
              [[t('models.th_ctx'), model.contextKnown ? formatK(model.contextLength) : '—'],
                [t('models.output_cap'), formatK(model.outputCapability)],
                [t('models.request_budget'), formatK(model.requestOutputBudget)],
                [t('models.th_input'), model.input?.includes('image') ? t('models.image_on') : t('models.image_off')],
                [t('models.th_reasoning'), reasoningLabel(model, t)],
              ].map(([label, value]) => React.createElement('div', { className: 'cb-metric', key: label },
                React.createElement('span', null, label),
                React.createElement('b', null, value),
              )),
            ),
          ),
        ),
        editing === model.id && form ? React.createElement('div', { className: 'cb-editor' },
            model.channelListed && !model.vendorReasoningNote ? null : React.createElement('div', { className: 'cb-section-desc cb-editor-note' }, model.channelListed ? model.vendorReasoningNote : t('models.unlisted_note')),
            React.createElement('div', { className: 'cb-section-desc cb-editor-note' }, t('models.count_hint')),
            React.createElement('label', { className: 'cb-field' }, React.createElement('span', { className: 'cb-field-label' }, t('models.context_ph')), React.createElement('input', { className: 'cb-input', value: form.contextWindow, onChange: (event) => setForm({ ...form, contextWindow: event.target.value }) })),
            React.createElement('label', { className: 'cb-field' }, React.createElement('span', { className: 'cb-field-label' }, t('models.cap_ph')), React.createElement('input', { className: 'cb-input', value: form.outputCapability, onChange: (event) => setForm({ ...form, outputCapability: event.target.value }) })),
            React.createElement('label', { className: 'cb-field' }, React.createElement('span', { className: 'cb-field-label' }, t('models.budget_ph')), React.createElement('input', { className: 'cb-input', value: form.requestOutputBudget, onChange: (event) => setForm({ ...form, requestOutputBudget: event.target.value }) })),
            React.createElement('label', { className: 'cb-field' }, React.createElement('span', { className: 'cb-field-label' }, t('models.th_input')), React.createElement('select', { className: 'cb-input', value: form.inputMode, onChange: (event) => setForm({ ...form, inputMode: event.target.value }) },
              ['inherit', 'text', 'text+image'].map((mode) => React.createElement('option', { key: mode, value: mode }, optionLabel(mode, t))))),
            React.createElement('label', { className: 'cb-field' }, React.createElement('span', { className: 'cb-field-label' }, t('models.th_reasoning')), React.createElement('select', { className: 'cb-input', value: form.reasoningMode, onChange: (event) => setForm({ ...form, reasoningMode: event.target.value }) },
              (model.vendorReasoningAvailable ? ['inherit', 'off', 'vendor'] : ['inherit', 'off']).map((mode) => React.createElement('option', { key: mode, value: mode }, optionLabel(mode, t))))),
            notice && notice.id === model.id ? React.createElement('div', { className: notice.ok ? 'cb-alert-ok cb-editor-note' : 'cb-alert-bad cb-editor-note' }, notice.text) : null,
            React.createElement('div', { className: 'cb-editor-actions' },
              React.createElement('button', {
                type: 'button',
                className: 'cb-btn cb-btn-primary',
                disabled: !!busy,
                onClick: () => saveEditor(model, false),
              }, t('models.save')),
              React.createElement('button', {
                type: 'button',
                className: 'cb-btn',
                disabled: !!busy,
                onClick: () => saveEditor(model, true),
              }, t('models.restore')),
            ),
          )
        : null,
      )),
    )
  )
}

// --- src/client/components/stats-section.js ---
function StatsSection({ status, t }) {
  return React.createElement(
    'div',
    { className: 'cb-section-card' },
    React.createElement('div', { className: 'cb-section-title' }, t('stats.title')),
    React.createElement('div', { className: 'cb-section-desc' }, t('stats.desc')),
    React.createElement(
      'table',
      { className: 'cb-table cb-facts' },
      React.createElement('thead', null, React.createElement('tr', null,
        React.createElement('th', null, t('stats.col_metric')),
        React.createElement('th', null, t('stats.col_value')),
      )),
      React.createElement('tbody', null, [
        [t('stats.requests'), `${status.sessionStats?.successfulRequests || 0} / ${status.sessionStats?.totalRequests || 0}`],
        [t('stats.tokens'), String(status.sessionStats?.totalTokensEst || 0)],
        [t('stats.latency'), status.sessionStats?.lastLatencyMs ? `${status.sessionStats.lastLatencyMs} ms` : '—'],
        [t('stats.last_req'), status.sessionStats?.lastRequestAt ? formatResetTime(status.sessionStats.lastRequestAt) : '—'],
      ].map(([label, value]) => React.createElement('tr', { key: label },
        React.createElement('th', { scope: 'row' }, label),
        React.createElement('td', { className: 'cb-num' }, value),
      )))
    )
  )
}

// --- src/client/components/diag-section.js ---
function DiagSection({ keyPresent, isRegistered, busy, smokeModels, smokeModel, onSmokeModel, smokeResult, handleSmoke, handleUnregister, handleRegister, t }) {
  return React.createElement(
    'div',
    { className: 'cb-section-card' },
    React.createElement('div', { className: 'cb-section-title' }, t('diag.title')),
    React.createElement('div', { className: 'cb-section-desc' }, t('diag.desc')),
    React.createElement(
      'label',
      { className: 'cb-field' },
      React.createElement('span', { className: 'cb-field-label' }, t('diag.model')),
      React.createElement(
        'select',
        {
          className: 'cb-input',
          value: smokeModel || '',
          disabled: !!busy || !(smokeModels || []).length,
          onChange: (event) => onSmokeModel(event.target.value),
        },
        (smokeModels || []).map((model) => React.createElement(
          'option',
          { key: model.id, value: model.id },
          `${model.name || model.id} · ${model.id}`,
        )),
      ),
    ),
    React.createElement(
      'div',
      { className: 'cb-row' },
      React.createElement(
        'button',
        {
          type: 'button',
          className: 'cb-btn',
          disabled: !!busy || !keyPresent,
          onClick: handleSmoke,
        },
        busy === 'smoke' ? t('diag.smoke_testing') : t('diag.smoke_btn')
      ),
      isRegistered
        ? React.createElement(
            'button',
            {
              type: 'button',
              className: 'cb-btn cb-btn-danger',
              disabled: !!busy,
              onClick: handleUnregister,
            },
            busy === 'unregister' ? t('diag.unregistering') : t('diag.unregister_btn')
          )
        : null,
      React.createElement(
        'button',
        {
          type: 'button',
          className: 'cb-btn cb-btn-primary',
          disabled: !!busy,
          onClick: handleRegister,
        },
        busy === 'register' ? t('diag.resyncing') : t('diag.resync_btn')
      )
    ),
    smokeResult
      ? React.createElement(
          'table',
          { className: 'cb-table cb-facts' },
          React.createElement('tbody', null, [
            [t('diag.col_latency'), smokeResult.latencyMs != null ? `${smokeResult.latencyMs} ms` : '—'],
            [t('diag.col_model'), smokeResult.model || '—'],
            [t('diag.col_reply'), smokeResult.preview || '—'],
          ].map(([label, value]) => React.createElement('tr', { key: label },
            React.createElement('th', { scope: 'row' }, label),
            React.createElement('td', null, value),
          ))),
        )
      : null
  )
}

// --- src/client/settings-page.js ---
function smokeChoices(models, config) {
  const all = Array.isArray(models) ? models : []
  const enabled = new Set(config?.enabledModels || [])
  const chosen = enabled.size ? all.filter((model) => enabled.has(model.id)) : all
  return chosen.length ? chosen : all
}

function pickSmokeModel(config, models) {
  const ids = models.map((model) => model.id)
  const preferred = config?.defaultModel || ''
  if (preferred && ids.includes(preferred)) return preferred
  if (ids.includes('cline-pass/deepseek-v4.1-flash')) return 'cline-pass/deepseek-v4.1-flash'
  return ids[0] || ''
}

function SettingsPage(props) {
  const t = props?.t || makeT(en, en)
  const scope = props?.scope || null
  const scopeError = props?.scopeError || ''

  const subscribe = React.useMemo(() => {
    return (cb) => {
      if (!scope?.subscribe) return () => {}
      try {
        return scope.subscribe(cb) || (() => {})
      } catch (_) {
        return () => {}
      }
    }
  }, [scope])

  const getSnapshot = React.useCallback(() => {
    if (!scope?.getSnapshot) return SNAPSHOT_LOADING
    try {
      return scope.getSnapshot() || SNAPSHOT_LOADING
    } catch (_) {
      return SNAPSHOT_LOADING
    }
  }, [scope])

  const snapshot = React.useSyncExternalStore(
    subscribe,
    getSnapshot,
    React.useCallback(() => SNAPSHOT_LOADING, [])
  )
  const snapshotStatus = snapshot?.status || 'loading'

  const [status, setStatus] = React.useState(null)
  const [draft, setDraft] = React.useState(null)
  const [busy, setBusy] = React.useState('')
  const [err, setErr] = React.useState('')
  const [msg, setMsg] = React.useState('')
  const [smokeResult, setSmokeResult] = React.useState(null)
  const [smokeModel, setSmokeModel] = React.useState('')

  // Plugin in-app updater state
  const [updateState, setUpdateState] = React.useState({
    checking: false,
    updating: false,
    currentVersion: '',
    latestVersion: '',
    updateAvailable: false,
    canAutoUpdate: true,
    error: '',
    notice: '',
  })

  // Key input state
  const [apiKeyInput, setApiKeyInput] = React.useState('')
  const [baseUrlInput, setBaseUrlInput] = React.useState('')
  const [showKey, setShowKey] = React.useState(false)

  // Accounts state
  const [newAccountLabel, setNewAccountLabel] = React.useState('')
  const [newAccountEnv, setNewAccountEnv] = React.useState('')
  const [showAddAccount, setShowAddAccount] = React.useState(false)

  // Filter & Search for Models
  const [modelsFilter, setModelsFilter] = React.useState('all')
  const [modelsSearch, setModelsSearch] = React.useState('')
  const [disabledModels, setDisabledModels] = React.useState([])
  const [advancedOpen, setAdvancedOpen] = React.useState(false)

  // Loopback fast login state
  const [fastLoginActive, setFastLoginActive] = React.useState(false)
  const [fastLoginNotice, setFastLoginNotice] = React.useState('')

  React.useEffect(() => {
    ensureCss()
  }, [])

  const load = React.useCallback(async () => {
    setErr('')
    const res = await fetch(`${ROUTE_PREFIX}/status`, { cache: 'no-store' })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`)
    setStatus(data)
    setDraft(data.config || {})
    setBaseUrlInput(data.config?.baseUrl || '')
    const choices = smokeChoices(data.availableModels, data.config)
    setSmokeModel((current) => (current && choices.some((model) => model.id === current) ? current : pickSmokeModel(data.config, choices)))
  }, [])

  React.useEffect(() => {
    load().catch((e) => setErr(String(e.message || e)))
  }, [load])

  const checkUpdate = React.useCallback(async () => {
    setUpdateState((s) => ({ ...s, checking: true, error: '' }))
    try {
      const res = await fetch(`${ROUTE_PREFIX}/update`)
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const data = await res.json().catch(() => ({}))
      setUpdateState((s) => ({
        ...s,
        checking: false,
        currentVersion: data.currentVersion || s.currentVersion,
        latestVersion: data.latestVersion || '',
        updateAvailable: !!data.updateAvailable,
        canAutoUpdate: data.canAutoUpdate !== false,
      }))
    } catch (_) {
      setUpdateState((s) => ({ ...s, checking: false }))
    }
  }, [])

  React.useEffect(() => {
    checkUpdate()
  }, [checkUpdate])

  async function handleTriggerUpdate() {
    if (updateState.updating) return
    setUpdateState((s) => ({ ...s, updating: true, error: '', notice: '' }))
    try {
      const res = await fetch(`${ROUTE_PREFIX}/update`, {
        method: 'POST',
        headers: { 'x-dsh-plugin-update': '1' },
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || data.ok === false || data.error) {
        throw new Error(data.error || `HTTP ${res.status}`)
      }
      const newVer = data.updatedVersion || updateState.latestVersion || updateState.currentVersion
      setUpdateState((s) => ({
        ...s,
        updating: false,
        updateAvailable: false,
        currentVersion: newVer,
        notice: t('update.done', { version: newVer }),
      }))
      setTimeout(() => checkUpdate(), 2000)
    } catch (err) {
      setUpdateState((s) => ({
        ...s,
        updating: false,
        error: t('update.failed', { error: String(err.message || err) }),
      }))
    }
  }

  async function handleSaveBaseUrl() {
    const next = String(baseUrlInput || '').trim()
    if (!next) {
      setErr(t('key.local_base', { url: '' }))
      return
    }
    setBusy('save-base')
    setErr('')
    setMsg('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/config`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ baseUrl: next }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || data.ok === false) throw new Error(data.error || `HTTP ${res.status}`)
      setMsg(t('key.save_base'))
      await load()
    } catch (error) {
      setErr(String(error.message || error))
    } finally {
      setBusy('')
    }
  }

  async function handleSaveKey() {
    const keyVal = String(apiKeyInput || '').trim()
    if (!keyVal) {
      setErr(t('key.empty_err'))
      return
    }
    setBusy('save-key')
    setErr('')
    setMsg('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/save-key`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ apiKey: keyVal, apiKeyEnv: draft?.apiKeyEnv }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      setApiKeyInput('')
      setMsg(data.validated
        ? t('key.saved_msg', { status: 'OK' })
        : t('key.saved_unverified', { error: data.validationError || `HTTP ${res.status}` }))
      await load()
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  async function handleRefreshQuota() {
    setBusy('refresh-quota')
    setErr('')
    setMsg('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/usage`)
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      setStatus((prev) => (prev ? { ...prev, usage: data } : prev))
      setMsg(t('quota.refreshed_msg'))
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  async function handleSyncPlanModels() {
    setBusy('sync-models')
    setErr('')
    setMsg('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/models/sync`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      setMsg(t('models.synced_msg', { total: data.totalModelsCount, discovered: data.discoveredCount }))
      await load()
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  async function handleRegister() {
    setBusy('register')
    setErr('')
    setMsg('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/register`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      const count = status?.availableModels?.filter((m) => !(draft?.disabledModels || []).includes(m.id)).length || 0
      setMsg(t('diag.resynced_msg', { count }))
      await load()
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  async function handleUnregister() {
    setBusy('unregister')
    setErr('')
    setMsg('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/unregister`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      setMsg(t('diag.unregistered_msg'))
      await load()
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  async function handleSmoke() {
    setBusy('smoke')
    setErr('')
    setSmokeResult(null)
    try {
      const res = await fetch(`${ROUTE_PREFIX}/smoke`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ model: smokeModel }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      setSmokeResult(data)
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  async function handleFastLogin() {
    setBusy('fast-login')
    setErr('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/auth/begin`, { method: 'POST' })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      if (data.authUrl) {
        window.open(data.authUrl, '_blank')
      }
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  async function handlePinAccount(accountEnv) {
    setBusy('pin-account')
    setErr('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/accounts/active`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ account: accountEnv }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || !data.ok) throw new Error(data.error || `HTTP ${res.status}`)
      await load()
    } catch (e) {
      setErr(String(e.message || e))
    } finally {
      setBusy('')
    }
  }

  const debounceTimerRef = typeof React.useRef === 'function' ? React.useRef(null) : { current: null }
  function debounceSaveDisabledModels(nextDisabled) {
    if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current)
    debounceTimerRef.current = setTimeout(async () => {
      try {
        const res = await fetch(`${ROUTE_PREFIX}/models/toggle`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ selectionKind: 'all-except-disabled', disabledModels: nextDisabled }),
        })
        const data = await res.json().catch(() => ({}))
        if (!res.ok || data.ok === false) throw new Error(data.error || `HTTP ${res.status}`)
        if (data.warning) setMsg(data.warning)
      } catch (error) {
        setErr(String(error.message || error))
      }
    }, 400)
  }

  async function saveModelPatch(body) {
    const local = !!(body && body.modelOverride)
    setBusy('model-edit')
    if (!local) setErr('')
    try {
      const res = await fetch(`${ROUTE_PREFIX}/models/toggle`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok || data.ok === false) throw new Error(data.error || `HTTP ${res.status}`)
      if (!local) setMsg(data.warning || t('models.saved'))
      await load()
      return { ok: true, message: data.warning || t('models.saved') }
    } catch (error) {
      const message = String(error.message || error)
      if (!local) setErr(message)
      return { ok: false, message }
    } finally {
      setBusy('')
    }
  }

  function handleToggleModel(id) {
    const all = status?.availableModels || []
    if ((draft?.selectionKind || status?.config?.selectionKind) === 'explicit') {
      const curr = new Set(draft?.explicitModels || [])
      if (curr.has(id)) curr.delete(id)
      else curr.add(id)
      const explicitModels = [...curr]
      setDraft({ ...draft, selectionKind: 'explicit', explicitModels, enabledModels: explicitModels })
      saveModelPatch({ selectionKind: 'explicit', explicitModels })
      return
    }
    const enabled = new Set(enabledIdsOf(draft, all))
    if (enabled.has(id)) enabled.delete(id)
    else enabled.add(id)
    const enabledIds = [...enabled]
    const next = all.map((model) => model.id).filter((modelId) => !enabled.has(modelId))
    setDraft({ ...draft, selectionKind: 'all-except-disabled', disabledModels: next, enabledModels: enabledIds })
    debounceSaveDisabledModels(next)
  }

  function enabledIdsOf(current, all) {
    if (current?.enabledModels?.length || current?.selectionKind === 'explicit') {
      return current.enabledModels || current.explicitModels || []
    }
    const disabled = new Set(current?.disabledModels || [])
    return all.map((model) => model.id).filter((modelId) => !disabled.has(modelId))
  }

  function handleSetModelsFilter(type) {
    setModelsFilter(type)
  }

  if (!scope && scopeError && !status) {
    return React.createElement(
      'div',
      { className: 'cb-page' },
      React.createElement('div', { className: 'cb-alert-err' }, scopeError),
      React.createElement('button', {
        type: 'button',
        className: 'cb-btn',
        style: { marginTop: '12px' },
        onClick: () => {
          setErr('')
          Promise.resolve(props.refreshScope?.()).then(() => load()).catch((error) => setErr(String(error.message || error)))
        },
      }, t('settings.retry'))
    )
  }

  if (!status || !draft) {
    if (err) {
      return React.createElement(
        'div',
        { className: 'cb-page' },
        React.createElement('div', { className: 'cb-alert cb-alert-err' }, `${t('settings.loading')}: ${err}`),
        React.createElement(
          'button',
          {
            type: 'button',
            className: 'cb-btn',
            style: { marginTop: '12px', alignSelf: 'flex-start' },
            onClick: () => {
              setErr('')
              load().catch((e) => setErr(String(e.message || e)))
            },
          },
          t('settings.retry')
        )
      )
    }
    return React.createElement('div', { className: 'cb-page' }, t('settings.loading'))
  }

  const healthOk = !!status.health?.ok
  const keyPresent = !!status.key?.present
  const isRegistered = !!status.isRegistered
  const modelsList = (status.availableModels || []).filter((model) => {
    if (modelsFilter === 'vision') return model.input?.includes('image') || model.vendorInput?.includes('image')
    if (modelsFilter === 'coding') return model.category === 'coding'
    if (modelsFilter === 'recommended') return model.recommended
    return true
  })
  const enabledSet = new Set(draft.enabledModels || status.config?.enabledModels || [])
  const enabledCount = (status.availableModels || []).filter((model) => enabledSet.has(model.id)).length
  const scopeNote = scopeError
    || (snapshotStatus === 'unavailable' ? t('settings.unavailable') : '')
    || (snapshotStatus === 'loading' ? t('settings.mirror_loading') : '')
  const usage = status.usage

  return React.createElement(
    'div',
    { className: 'cb-page' },

    // Page Header
    React.createElement(
      'div',
      { className: 'cb-status' },
      React.createElement('span', { className: `cb-badge ${healthOk ? 'cb-badge-ok' : 'cb-badge-bad'}` }, healthOk ? t('badge.online', { latency: status.health?.latencyMs }) : t('badge.offline')),
      React.createElement('span', { className: `cb-badge ${keyPresent ? 'cb-badge-ok' : 'cb-badge-warn'}` }, keyPresent ? t('badge.key_ok', { source: status.key?.source }) : t('badge.key_missing')),
      React.createElement('span', { className: `cb-badge ${isRegistered ? 'cb-badge-ok' : 'cb-badge-warn'}` }, isRegistered ? t('badge.registered', { count: enabledCount }) : t('badge.not_registered')),
    ),

    // In-app Update Bar
    React.createElement(UpdateBanner, { updateState, handleTriggerUpdate, t }),

    // Notifications
    scopeNote ? React.createElement('div', { className: 'cb-banner-warning' }, scopeNote) : null,
    err ? React.createElement('div', { className: 'cb-alert-bad' }, err) : null,
    msg ? React.createElement('div', { className: 'cb-alert-ok' }, msg) : null,

    // Card 1: API Key and Credentials
    React.createElement(KeySection, {
      keyPresent,
      apiKeyInput,
      setApiKeyInput,
      showKey,
      setShowKey,
      busy,
      draft,
      baseUrlInput,
      setBaseUrlInput,
      handleSaveKey,
      handleSaveBaseUrl,
      handleFastLogin,
      t,
    }),

    // Accounts Pool Card
    React.createElement(AccountsSection, { status, busy, handlePinAccount, t }),

    // Quota Warning & Dashboard Card
    React.createElement(QuotaSection, { keyPresent, status, usage, busy, handleRefreshQuota, t }),

    // Card 3: Model Picker Management
    React.createElement(ModelsSection, {
      modelsList,
      enabledSet,
      enabledCount,
      totalCount: (status.availableModels || []).length,
      keyPresent,
      busy,
      modelsFilter,
      providerReasoning: draft.providerReasoning || '',
      handleSyncPlanModels,
      handleSetModelsFilter,
      handleToggleModel,
      saveModelPatch,
      t,
    }),

    // Card 4: Session Metrics & Usage Tracking
    React.createElement(StatsSection, { status, t }),

    // Card 5: Diagnostics & Sync with DSH
    React.createElement(DiagSection, {
      keyPresent,
      isRegistered,
      busy,
      smokeModels: smokeChoices(status.availableModels, draft),
      smokeModel,
      onSmokeModel: (id) => {
        setSmokeModel(id)
        setDraft((prev) => ({ ...(prev || {}), defaultModel: id }))
        fetch(`${ROUTE_PREFIX}/models/toggle`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ defaultModel: id }),
        }).then(async (res) => {
          const data = await res.json().catch(() => ({}))
          if (!res.ok || data.ok === false) throw new Error(data.error || `HTTP ${res.status}`)
        }).catch((e) => setErr(String(e.message || e)))
      },
      smokeResult,
      handleSmoke,
      handleUnregister,
      handleRegister,
      t,
    })
  )
}

// --- src/client/plugin-card.js ---
function PluginCard(props) {
  const page = !!(props && props.view === 'page')
  const [open, setOpen] = React.useState(!!page)
  const t = props?.t || makeT(en, en)
  React.useEffect(() => {
    ensureCss()
  }, [])

  // Summary view: the host page draws the title, so this is only the one-liner.
  if (props && props.view === 'summary') {
    return React.createElement('span', { style: { fontSize: '13px', color: 'var(--dsw-alias-label-secondary)' } }, t('subtitle'))
  }

  return React.createElement(
    page ? 'div' : 'li',
    { className: page ? 'cb-page' : 'cb-section-card', style: page ? undefined : { listStyle: 'none', marginBottom: '12px' } },
    React.createElement(
      'button',
      {
        type: 'button',
        style: {
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          display: page ? 'none' : 'flex',
          alignItems: 'center',
          width: '100%',
          padding: 0,
          textAlign: 'left',
        },
        'aria-expanded': page ? true : open,
        onClick: () => setOpen((v) => !v),
      },
      React.createElement(
        'div',
        { style: { flex: 1 } },
        React.createElement('div', { style: { fontWeight: 600, fontSize: '15px' } }, t('title')),
        React.createElement('div', { style: { fontSize: '13px', color: 'var(--dsw-alias-label-secondary)' } }, t('subtitle'))
      ),
      React.createElement('span', { className: 'cb-chevron' + (open ? ' cb-chevron-open' : '') },
        React.createElement(Chevron)
      )
    ),
    (page || open)
      ? React.createElement(
          'div',
          { style: { marginTop: page ? 0 : '12px' } },
          React.createElement(
            ErrorBoundary,
            null,
            React.createElement(SettingsPage, props)
          )
        )
      : null
  )
}

// --- src/client/entry.js ---
const INJECT = ['configForms', 'slots', 'locale']
const ROW_KEY = `${PACKAGE_NAME}#${NS}`

function bindScope(ctx) {
  try {
    if (!ctx || typeof ctx.configForms?.get !== 'function') {
      return { scope: null, scopeError: 'This DSH build did not provide configForms. The plugin needs @deepseek-ai/dsh-client-ui-settings (tested on DSH 0.1.7-rc.2).' }
    }
    return { scope: ctx.configForms.get(NS), scopeError: '' }
  } catch (err) {
    return { scope: null, scopeError: String(err?.message || err) }
  }
}

function refreshScope(ctx) {
  try {
    const face = ctx.configForms?.describe?.()
    if (typeof face?.ensure === 'function') return face.ensure()
  } catch (err) {
    return Promise.reject(err)
  }
  return Promise.resolve()
}

function apply(ctx) {
  const bound = bindScope(ctx)
  const card = (props) => React.createElement(
    ErrorBoundary,
    null,
    React.createElement(PluginCard, {
      ...props,
      scope: bound.scope,
      scopeError: bound.scopeError,
      refreshScope: () => refreshScope(ctx),
    }),
  )

  const addLocale = (locale, dictionary) => {
    try {
      return ctx.locale.register(NS, locale, dictionary)
    } catch (_) {
      return () => {}
    }
  }

  if (typeof ctx.effect === 'function') {
    ctx.effect(() => {
      const undo = []
      if (ctx.locale && ctx.locale.register) {
        undo.push(addLocale('en', en), addLocale('zh', zh))
      }
      return () => {
        for (const off of undo) {
          try { off?.() } catch { /* already gone */ }
        }
      }
    }, 'dsh-clinebot: dictionaries')

    ctx.effect(() => {
      if (!ctx.slots || typeof ctx.slots.inject !== 'function') return undefined
      const surface = (props) => card({ ...props, view: props?.view || 'page' })
      const label = () => {
        try {
          const translate = ctx.locale?.bind?.(NS)
          if (typeof translate === 'function') return translate('title')
        } catch (_) {}
        return 'ClineBot'
      }
      const offs = []
      const listen = (register) => {
        try {
          const off = register()
          if (typeof off === 'function') offs.push(off)
        } catch (err) {
          console.warn('[dsh-clinebot] settings registration failed:', err)
        }
      }
      listen(() => ctx.slots.inject('settings.section', () => ctx.slots.register(
        {
          name: 'settings.section',
          id: NS,
          order: 80,
          label,
          locale: NS,
        },
        surface,
      )))
      listen(() => ctx.slots.inject('plugins.row.config', () => ctx.slots.register(
        {
          name: 'plugins.row.config',
          key: ROW_KEY,
          locale: NS,
        },
        surface,
      )))
      return () => {
        for (const off of offs) {
          try { off() } catch { /* slot already disposed */ }
        }
      }
    }, 'dsh-clinebot: settings card')
  }

  return { scope: bound.scope, scopeError: bound.scopeError }
}

module.exports = { apply, inject: INJECT }

    return module.exports
  },
})
