import { readFileSync, writeFileSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'
import path from 'node:path'

const root = fileURLToPath(new URL('../', import.meta.url))
const srcDir = path.join(root, 'src', 'client')
const outFile = path.join(root, 'lib', 'client.js')

const files = [
  'constants.js',
  'locales.js',
  'chevron.js',
  'styles.js',
  'error-boundary.js',
  'progress-bar.js',
  'components/update-banner.js',
  'components/key-section.js',
  'components/accounts-section.js',
  'components/quota-section.js',
  'components/models-section.js',
  'components/stats-section.js',
  'components/diag-section.js',
  'settings-page.js',
  'plugin-card.js',
  'entry.js',
]

const parts = files.map((rel) => {
  const code = readFileSync(path.join(srcDir, rel), 'utf8')
  return `// --- src/client/${rel} ---\n` + code.trim()
})

const bundle = `// @generated by scripts/build-client.js - DO NOT EDIT DIRECTLY.
// Edit modular source files in src/client/ instead.

window.__ModuleLoader__.load({
  id: ${JSON.stringify(JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8')).name)},
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    let React = require('react')

${parts.join('\n\n')}

    return module.exports
  },
})
`

writeFileSync(outFile, bundle, 'utf8')
const stats = statSync(outFile)
console.log(`[build-client] Rebuilt lib/client.js: ${stats.size} bytes (< 256 KiB limit)`)

if (stats.size > 262144) {
  console.error('[build-client] ERROR: lib/client.js exceeds official DSH Store limit (262144 bytes)!')
  process.exit(1)
}

try {
  execFileSync(process.execPath, ['--check', outFile], { stdio: 'inherit' })
  console.log('[build-client] Syntax check: OK')
} catch (err) {
  console.error('[build-client] Syntax error in assembled lib/client.js!')
  process.exit(1)
}
